spring:
  application:
    name: 'fornecedor'
  datasource:
    username: root
    password: '@Admin123'
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
